import data from './bandArticles.json';

/**
 * The Heavenly Band's essays — the written half of the network.
 *
 * GENERATED by scripts/build-band-articles.mjs from the site's own catalogue.
 * Metadata only: the prose is ~950KB across 113 essays and is fetched per
 * article by `src/services/band/articleBody.ts`, not shipped.
 *
 * Synchronous getters over a module-level Map, like `stationCatalog.ts` and
 * `stationArticles.ts` — the data is bundled, so there is nothing to await and
 * a screen can resolve its subject during render.
 */

export interface BandMember {
  id: string;
  name: string;
  /** First name alone, e.g. "Nova". */
  short: string;
  /** One-line beat, e.g. "For the doubting". Shown under the byline. */
  focus: string;
}

export interface BandArticle {
  slug: string;
  /** The eyebrow above the title. Decorative on the site — nothing filters by it. */
  kicker: string;
  title: string;
  /** One-sentence standfirst. Doubles as the card's excerpt AND the article's lead. */
  dek: string;
  /** A STATION slug, not a path: it names the station whose gradient backs the card. */
  image: string;
  /** A `BandMember.id`. */
  author: string;
  /** Pull-quote sentence, shown in the callout. */
  stands: string;
  /** Root-relative on kjubilee.com — resolve with `articleImageUrl`. */
  img: string;
  /** Build-time word count, the source for reading time. */
  words: number;
  /** Set on the one article about what is broadcasting today. */
  live?: boolean;
}

interface BandArticlesFile {
  members: Record<string, BandMember>;
  articles: BandArticle[];
}

const FILE = data as unknown as BandArticlesFile;

/**
 * Authored order, exactly as published — there is NO date anywhere in this
 * data, so there is nothing to sort by and nothing to show. The order is
 * editorial: the general essays about the band first, then twelve runs of seven
 * by each member who writes.
 */
const ARTICLES = FILE.articles;
const BY_SLUG = new Map(ARTICLES.map((a) => [a.slug, a]));

/** Every essay, in the order the band publishes them. */
export function allBandArticles(): BandArticle[] {
  return ARTICLES;
}

export function bandArticle(slug: string): BandArticle | undefined {
  return BY_SLUG.get(slug);
}

export function bandMember(id: string | undefined): BandMember | undefined {
  return id ? FILE.members[id] : undefined;
}

/**
 * Reading time in whole minutes, at the site's own 220 words per minute, never
 * less than one. Kept identical so the two never disagree about the same essay.
 */
export function readingMinutes(words: number | undefined): number {
  return Math.max(1, Math.ceil((words || 0) / 220));
}

/**
 * Article art lives on the website rather than in the bundle: 113 pictures would
 * dwarf the app, and Metro can only resolve `require()` from string literals, so
 * bundling them would mean a generated 113-entry map like `stationArt.ts`.
 *
 * The `?v=` is the site's own cache-buster, carried so a re-cropped picture
 * reaches the app the same day it reaches the web.
 */
const COVER_V = '20260825a';
const SITE = 'https://kjubilee.com';

export function articleImageUrl(article: BandArticle): string {
  return `${SITE}${article.img}?v=${COVER_V}`;
}
